name: tests

on:
  push:
    branches-ignore:
      -main

jobs:
  run-all-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          check-latest: true

#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: build

      - name: Run build with Gradle Wrapper
        run: ./gradlew build